/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devis;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.Enumeration;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTextField;


/**
 *
 * @author kevin
 */
public class Main extends javax.swing.JFrame {

    public int rawTotalValue = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton afficherPrixButton;
    private javax.swing.JTextField alimentationValue;
    private javax.swing.JTextField boitierValue;
    private javax.swing.JTextField cgValue;
    private javax.swing.JTextField cmValue;
    private javax.swing.JComboBox<String> comboAlimentation;
    private javax.swing.JComboBox<String> comboBoitier;
    private javax.swing.JComboBox<String> comboCG;
    private javax.swing.JComboBox<String> comboCM;
    private javax.swing.JComboBox<String> comboCpu;
    private javax.swing.JComboBox<String> comboDisque;
    private javax.swing.JComboBox<String> comboDisque2;
    private javax.swing.JComboBox<String> comboEcran;
    private javax.swing.JComboBox<String> comboLecteur;
    private javax.swing.JComboBox<String> comboPrix;
    private javax.swing.JComboBox<String> comboRam;
    private javax.swing.JComboBox<String> comboVentillo;
    private javax.swing.JTextField cpuValue;
    private javax.swing.JTextField disk2Value;
    private javax.swing.JTextField disqueValue;
    private javax.swing.JTextField ecranValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbAlimentation;
    private javax.swing.JLabel lbBoitier;
    private javax.swing.JLabel lbCg;
    private javax.swing.JLabel lbCm;
    private javax.swing.JLabel lbCpu;
    private javax.swing.JLabel lbDisk;
    private javax.swing.JLabel lbDisk2;
    private javax.swing.JLabel lbEcran;
    private javax.swing.JLabel lbLecteur;
    private javax.swing.JLabel lbRam;
    private javax.swing.JLabel lbVentillo;
    private javax.swing.JTextField lecteurValue;
    private javax.swing.JSlider merge;
    private javax.swing.JTextField mergeValue;
    private javax.swing.JTextField ramValue;
    private javax.swing.JLabel sliderValue;
    private javax.swing.JTextField totalValue;
    private javax.swing.JTextField ventilloValue;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MainWindow
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        comboCpu = new JComboBox(new MyConnection().getItems("cpu").toArray());
        cpuValue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboCM = new JComboBox(new MyConnection().getItems("cm").toArray());
        cmValue = new javax.swing.JTextField();
        ramValue = new javax.swing.JTextField();
        comboRam = new JComboBox(new MyConnection().getItems("ram").toArray());
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        disqueValue = new javax.swing.JTextField();
        comboDisque = new JComboBox(new MyConnection().getItems("disk").toArray());
        ventilloValue = new javax.swing.JTextField();
        comboVentillo = new JComboBox(new MyConnection().getItems("ventillo").toArray());
        ;
        jLabel10 = new javax.swing.JLabel();
        comboBoitier = new JComboBox(new MyConnection().getItems("boitier").toArray())
        ;
        jLabel11 = new javax.swing.JLabel();
        boitierValue = new javax.swing.JTextField();
        comboAlimentation = new JComboBox(new MyConnection().getItems("alimentation").toArray());
        ;
        jLabel12 = new javax.swing.JLabel();
        alimentationValue = new javax.swing.JTextField();
        comboEcran = new JComboBox(new MyConnection().getItems("ecran").toArray());
        ecranValue = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        afficherPrixButton = new javax.swing.JToggleButton();
        cgValue = new javax.swing.JTextField();
        comboCG = new JComboBox(new MyConnection().getItems("cg").toArray());
        merge = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        comboPrix = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboLecteur = new JComboBox(new MyConnection().getItems("dvd").toArray());
        ;
        lecteurValue = new javax.swing.JTextField();
        mergeValue = new javax.swing.JTextField();
        sliderValue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbCpu = new javax.swing.JLabel();
        lbCm = new javax.swing.JLabel();
        lbRam = new javax.swing.JLabel();
        lbCg = new javax.swing.JLabel();
        lbDisk = new javax.swing.JLabel();
        lbLecteur = new javax.swing.JLabel();
        lbBoitier = new javax.swing.JLabel();
        lbAlimentation = new javax.swing.JLabel();
        lbEcran = new javax.swing.JLabel();
        lbVentillo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboDisque2 = new JComboBox(new MyConnection().getItems("disk").toArray());
        disk2Value = new javax.swing.JTextField();
        lbDisk2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expert de Mountage");
        setBounds(new java.awt.Rectangle(400, 0, 0, 0));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("CPU: ");

        comboCpu.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboCpu.setAlignmentX(0.0F);
        comboCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCpuActionPerformed(evt);
            }
        });

        cpuValue.setText(String.valueOf(0));
        cpuValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cpuValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpuValueFocusLost(evt);
            }
        });
        cpuValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpuValueKeyPressed(evt);
            }
        });

        jLabel7.setText("Carte Mere:");

        comboCM.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboCM.setAlignmentX(0.0F);
        comboCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCMActionPerformed(evt);
            }
        });

        cmValue.setText(String.valueOf(0));
        cmValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cmValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmValueFocusLost(evt);
            }
        });
        cmValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmValueKeyPressed(evt);
            }
        });

        ramValue.setText(String.valueOf(0));
        ramValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        ramValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ramValueFocusLost(evt);
            }
        });
        ramValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramValueActionPerformed(evt);
            }
        });
        ramValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ramValueKeyPressed(evt);
            }
        });

        comboRam.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboRam.setAlignmentX(0.0F);
        comboRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRamActionPerformed(evt);
            }
        });

        jLabel8.setText("RAM:");

        jLabel9.setText("Disque : ");

        disqueValue.setText(String.valueOf(0));
        disqueValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        disqueValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                disqueValueFocusLost(evt);
            }
        });
        disqueValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disqueValueActionPerformed(evt);
            }
        });
        disqueValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                disqueValueKeyPressed(evt);
            }
        });

        comboDisque.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboDisque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDisqueActionPerformed(evt);
            }
        });

        ventilloValue.setText(String.valueOf(0));
        ventilloValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        ventilloValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ventilloValueFocusLost(evt);
            }
        });
        ventilloValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ventilloValueKeyPressed(evt);
            }
        });

        comboVentillo.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboVentillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVentilloActionPerformed(evt);
            }
        });

        jLabel10.setText("Ventillo:");

        comboBoitier.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboBoitier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoitierActionPerformed(evt);
            }
        });

        jLabel11.setText("Boitier:");

        boitierValue.setText(String.valueOf(0));
        boitierValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        boitierValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                boitierValueFocusLost(evt);
            }
        });
        boitierValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boitierValueKeyPressed(evt);
            }
        });

        comboAlimentation.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboAlimentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlimentationActionPerformed(evt);
            }
        });

        jLabel12.setText("Alimentation:");

        alimentationValue.setText(String.valueOf(0));
        alimentationValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        alimentationValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alimentationValueFocusLost(evt);
            }
        });
        alimentationValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alimentationValueKeyPressed(evt);
            }
        });

        comboEcran.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboEcran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEcranActionPerformed(evt);
            }
        });

        ecranValue.setText(String.valueOf(0));
        ecranValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        ecranValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ecranValueFocusLost(evt);
            }
        });
        ecranValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecranValueActionPerformed(evt);
            }
        });
        ecranValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ecranValueKeyPressed(evt);
            }
        });

        jLabel13.setText("Ecran:");

        totalValue.setText("0");
        totalValue.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        totalValue.setForeground(new java.awt.Color(47, 253, 79));
        totalValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalValueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Total:");
        jLabel1.setAlignmentX(Component
            .LEFT_ALIGNMENT);

        afficherPrixButton.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        afficherPrixButton.setText("Afficher Prix");
        afficherPrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherPrixButtonActionPerformed(evt);
            }
        });

        cgValue.setText(String.valueOf(0));
        cgValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cgValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cgValueFocusLost(evt);
            }
        });
        cgValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cgValueKeyPressed(evt);
            }
        });

        comboCG.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboCG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCGActionPerformed(evt);
            }
        });

        merge.setMajorTickSpacing(10);
        merge.setMinorTickSpacing(10);
        merge.setPaintLabels(true);
        merge.setPaintTicks(true);
        merge.setToolTipText("");
        merge.setValue(10);
        merge.setDoubleBuffered(true);
        merge.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mergeStateChanged(evt);
            }
        });

        jLabel16.setText("Carte Graphique:");

        comboPrix.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboPrix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIX_ACHAT", "PRIX_GROS", "PRIX_DETAIL" }));
        comboPrix.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPrixItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Prix de Vente: ");

        jLabel17.setText("Lecteur:");

        comboLecteur.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboLecteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLecteurActionPerformed(evt);
            }
        });

        lecteurValue.setText(String.valueOf(0));
        lecteurValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lecteurValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lecteurValueFocusLost(evt);
            }
        });
        lecteurValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecteurValueActionPerformed(evt);
            }
        });
        lecteurValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lecteurValueKeyPressed(evt);
            }
        });

        mergeValue.setText("0");
        mergeValue.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        mergeValue.setForeground(new java.awt.Color(241, 26, 26));
        mergeValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mergeValueKeyPressed(evt);
            }
        });

        sliderValue.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        sliderValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sliderValue.setText(String.valueOf(merge.getValue()));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("%");

        lbCpu.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbCm.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbRam.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbCg.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbDisk.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbLecteur.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbBoitier.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbAlimentation.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbEcran.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        lbVentillo.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jLabel3.setText("Disque2:");

        comboDisque2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        comboDisque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDisque2ActionPerformed(evt);
            }
        });

        disk2Value.setText(String.valueOf(0));
        disk2Value.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        disk2Value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                disk2ValueFocusLost(evt);
            }
        });
        disk2Value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                disk2ValueKeyPressed(evt);
            }
        });

        lbDisk2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jMenu1.setText("Menu");

        jMenuItem1.setText("Imprimer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Articles");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboCM, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbCm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboRam, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ramValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbRam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(comboCG, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cgValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbCg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboDisque, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(disqueValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(comboDisque2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(disk2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbDisk2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(comboVentillo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ventilloValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbVentillo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboLecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lecteurValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbLecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboBoitier, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boitierValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbBoitier, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(comboAlimentation, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alimentationValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbAlimentation, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboEcran, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ecranValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbEcran, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(merge, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(sliderValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(mergeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(totalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(comboPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(afficherPrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cpuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(lbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(afficherPrixButton))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboCM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmValue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ramValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbRam, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboCG, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cgValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbCg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(disqueValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDisque, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisk2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(disk2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboDisque2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(comboVentillo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ventilloValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbVentillo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecteurValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoitier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boitierValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBoitier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboAlimentation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alimentationValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAlimentation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecranValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEcran, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEcran, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(merge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(mergeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCpuActionPerformed
        cpuValue.setText(new MyConnection().getValue(comboCpu.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbCpu.setText(new MyConnection().getValue(comboCpu.getSelectedItem().toString(), "Prix_Achat"));        
        updateMergeValue();
    }//GEN-LAST:event_comboCpuActionPerformed

    private void comboPrixItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPrixItemStateChanged
        if(comboPrix.getSelectedItem().toString().equals("PRIX_GROS") || comboPrix.getSelectedItem().toString().equals("PRIX_DETAIL")){
            merge.setValue(0);
        }else if(comboPrix.getSelectedItem().toString().equals("PRIX_ACHAT") && merge.getValue() == 0){
            merge.setValue(10);
        }
        cpuValue.setText(new MyConnection().getValue(comboCpu.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        cmValue.setText(new MyConnection().getValue(comboCM.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        ramValue.setText(new MyConnection().getValue(comboRam.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        cgValue.setText(new MyConnection().getValue(comboCG.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        disqueValue.setText(new MyConnection().getValue(comboDisque.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        disk2Value.setText(new MyConnection().getValue(comboDisque2.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        ventilloValue.setText(new MyConnection().getValue(comboVentillo.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lecteurValue.setText(new MyConnection().getValue(comboLecteur.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        boitierValue.setText(new MyConnection().getValue(comboBoitier.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        alimentationValue.setText(new MyConnection().getValue(comboAlimentation.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        updateMergeValue();
    }//GEN-LAST:event_comboPrixItemStateChanged

    private void comboCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCMActionPerformed
        cmValue.setText(new MyConnection().getValue(comboCM.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbCm.setText(new MyConnection().getValue(comboCM.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboCMActionPerformed

    private void comboRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRamActionPerformed
        ramValue.setText(new MyConnection().getValue(comboRam.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbRam.setText(new MyConnection().getValue(comboRam.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboRamActionPerformed

    private void comboDisqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDisqueActionPerformed
        disqueValue.setText(new MyConnection().getValue(comboDisque.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbDisk.setText(new MyConnection().getValue(comboDisque.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboDisqueActionPerformed

    private void comboVentilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVentilloActionPerformed
        ventilloValue.setText(new MyConnection().getValue(comboVentillo.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbVentillo.setText(new MyConnection().getValue(comboVentillo.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboVentilloActionPerformed

    private void comboLecteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLecteurActionPerformed
        lecteurValue.setText(new MyConnection().getValue(comboLecteur.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbLecteur.setText(new MyConnection().getValue(comboLecteur.getSelectedItem().toString(), "Prix_Achat"));

        updateMergeValue();
    }//GEN-LAST:event_comboLecteurActionPerformed

    private void comboBoitierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoitierActionPerformed
        boitierValue.setText(new MyConnection().getValue(comboBoitier.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbBoitier.setText(new MyConnection().getValue(comboBoitier.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboBoitierActionPerformed

    private void comboAlimentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlimentationActionPerformed
        alimentationValue.setText(new MyConnection().getValue(comboAlimentation.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbAlimentation.setText(new MyConnection().getValue(comboAlimentation.getSelectedItem().toString(), "Prix_Achat"));

        updateMergeValue();
    }//GEN-LAST:event_comboAlimentationActionPerformed

    private void comboEcranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEcranActionPerformed
        ecranValue.setText(new MyConnection().getValue(comboEcran.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbEcran.setText(new MyConnection().getValue(comboEcran.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboEcranActionPerformed

    private void mergeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mergeStateChanged
        sliderValue.setText(String.valueOf(merge.getValue()));
        updateMergeValue();
    }//GEN-LAST:event_mergeStateChanged

    private void cpuValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpuValueFocusLost
          valueFocusLost(cpuValue, comboCpu);
    }//GEN-LAST:event_cpuValueFocusLost

    private void cpuValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpuValueKeyPressed
          valueKeyPressed(evt, cpuValue, cmValue);
    }//GEN-LAST:event_cpuValueKeyPressed

    private void cmValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmValueFocusLost
        valueFocusLost(cmValue, comboCM);
    }//GEN-LAST:event_cmValueFocusLost

    private void cmValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmValueKeyPressed
        valueKeyPressed(evt, cmValue, ramValue);
    }//GEN-LAST:event_cmValueKeyPressed

    private void ramValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ramValueFocusLost
        valueFocusLost(ramValue, comboRam);
    }//GEN-LAST:event_ramValueFocusLost

    private void ramValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ramValueKeyPressed
        valueKeyPressed(evt, ramValue, cgValue);
    }//GEN-LAST:event_ramValueKeyPressed

    private void cgValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cgValueFocusLost
        valueFocusLost(cgValue, comboCG);
    }//GEN-LAST:event_cgValueFocusLost

    private void cgValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cgValueKeyPressed
        valueKeyPressed(evt, cgValue, disqueValue);
    }//GEN-LAST:event_cgValueKeyPressed

    private void disqueValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_disqueValueFocusLost
        valueFocusLost(disqueValue, comboDisque);
    }//GEN-LAST:event_disqueValueFocusLost

    private void disqueValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disqueValueKeyPressed
        valueKeyPressed(evt, disqueValue, disk2Value);
    }//GEN-LAST:event_disqueValueKeyPressed

    private void ventilloValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ventilloValueFocusLost
        valueFocusLost(ventilloValue, comboVentillo);
    }//GEN-LAST:event_ventilloValueFocusLost

    private void ventilloValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ventilloValueKeyPressed
        valueKeyPressed(evt, ventilloValue, lecteurValue);
    }//GEN-LAST:event_ventilloValueKeyPressed

    private void lecteurValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lecteurValueFocusLost
        valueFocusLost(lecteurValue, comboLecteur);
    }//GEN-LAST:event_lecteurValueFocusLost

    private void lecteurValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lecteurValueKeyPressed
        valueKeyPressed(evt, lecteurValue, boitierValue);
    }//GEN-LAST:event_lecteurValueKeyPressed

    private void boitierValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boitierValueFocusLost
        valueFocusLost(boitierValue, comboBoitier);
    }//GEN-LAST:event_boitierValueFocusLost

    private void boitierValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boitierValueKeyPressed
        valueKeyPressed(evt, boitierValue, alimentationValue);
    }//GEN-LAST:event_boitierValueKeyPressed

    private void alimentationValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alimentationValueFocusLost
        valueFocusLost(alimentationValue, comboAlimentation);
    }//GEN-LAST:event_alimentationValueFocusLost

    private void alimentationValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alimentationValueKeyPressed
        valueKeyPressed(evt, alimentationValue, ecranValue);
    }//GEN-LAST:event_alimentationValueKeyPressed

    private void ecranValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ecranValueFocusLost
        valueFocusLost(ecranValue, comboEcran);
    }//GEN-LAST:event_ecranValueFocusLost

    private void ecranValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ecranValueKeyPressed
        
    }//GEN-LAST:event_ecranValueKeyPressed

    private void mergeValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mergeValueKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                Integer.parseInt(mergeValue.getText());
                updateRawTotalValue();
                int realTotalValue = this.rawTotalValue;
                int oldValue = Integer.valueOf(mergeValue.getText());
                int percent = oldValue * 100 / rawTotalValue;
                merge.setValue(percent);
                mergeValue.setText(String.valueOf(oldValue));
                totalValue.setText(String.valueOf(Integer.valueOf(mergeValue.getText()) + realTotalValue));
            } catch (NumberFormatException e) {
            }
//            try {
//                Integer.parseInt(mergeValue.getText());
//                updateRawTotalValue();
//                this.changeJustSlider = true;
//                if(Integer.valueOf(mergeValue.getText()) >= this.rawTotalValue){
//                    merge.setValue(100);
//                } else {
//                    merge.setValue((Integer.valueOf(mergeValue.getText())*100/this.rawTotalValue));
//                }
//                totalValue.requestFocusInWindow();
//            } catch (NumberFormatException e) {
//                e.printStackTrace(); 
//            }
        }
    }//GEN-LAST:event_mergeValueKeyPressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // save Selected Data if not changed.
        int[] selectedDataIndex = new int[11];
        JComboBox[] selectedDataType = {comboCpu, comboCM, comboRam, comboCG, comboDisque, comboDisque2, comboVentillo, comboLecteur, comboBoitier, comboAlimentation, comboEcran};
        for(int i = 0; i < selectedDataIndex.length; i++){
            selectedDataIndex[i] = selectedDataType[i].getSelectedIndex();
        }
        new Articles(this).setVisible(true);
        // Load the new Data.
        loadComboValues();
        // Restore selected data.
        for(int i = 0; i < selectedDataIndex.length; i++){
            selectedDataType[i].setSelectedIndex(selectedDataIndex[i]);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void comboCGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCGActionPerformed
        cgValue.setText(new MyConnection().getValue(comboCG.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbCg.setText(new MyConnection().getValue(comboCG.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboCGActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Print(this, comboCpu.getSelectedItem().toString(), comboCM.getSelectedItem().toString(), comboRam.getSelectedItem().toString(), comboCG.getSelectedItem().toString(), comboDisque.getSelectedItem().toString(), comboDisque2.getSelectedItem().toString(), comboAlimentation.getSelectedItem().toString(), comboEcran.getSelectedItem().toString(), comboLecteur.getSelectedItem().toString(), Integer.valueOf(totalValue.getText())).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void afficherPrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherPrixButtonActionPerformed
        cpuValue.setVisible(!cpuValue.isVisible());
        ramValue.setVisible(!ramValue.isVisible());
        disqueValue.setVisible(!disqueValue.isVisible());
        disk2Value.setVisible(!disk2Value.isVisible());
        cgValue.setVisible(!cgValue.isVisible());
        cmValue.setVisible(!cmValue.isVisible());
        ventilloValue.setVisible(!ventilloValue.isVisible());
        lecteurValue.setVisible(!lecteurValue.isVisible());
        boitierValue.setVisible(!boitierValue.isVisible());
        alimentationValue.setVisible(!alimentationValue.isVisible());
        ecranValue.setVisible(!ecranValue.isVisible());
        mergeValue.setVisible(!mergeValue.isVisible());
    }//GEN-LAST:event_afficherPrixButtonActionPerformed

    private void lecteurValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecteurValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecteurValueActionPerformed

    private void ramValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramValueActionPerformed

    private void totalValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalValueActionPerformed

    private void ecranValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecranValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecranValueActionPerformed

    private void comboDisque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDisque2ActionPerformed
        disk2Value.setText(new MyConnection().getValue(comboDisque2.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
        lbDisk2.setText(new MyConnection().getValue(comboDisque2.getSelectedItem().toString(), "Prix_Achat"));
        updateMergeValue();
    }//GEN-LAST:event_comboDisque2ActionPerformed

    private void disk2ValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_disk2ValueFocusLost
        valueFocusLost(disk2Value, comboDisque2);
    }//GEN-LAST:event_disk2ValueFocusLost

    private void disk2ValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disk2ValueKeyPressed
        valueKeyPressed(evt, disk2Value, ventilloValue);
    }//GEN-LAST:event_disk2ValueKeyPressed

    private void disqueValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disqueValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disqueValueActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void updateMergeValue(){
        updateRawTotalValue();
        int mv = (this.rawTotalValue * this.merge.getValue()) / 100;
        mergeValue.setText(String.valueOf(mv));
        updateTotalValue();
    }
   
    public void updateRawTotalValue(){
        rawTotalValue = Integer.valueOf(cpuValue.getText())+
                Integer.valueOf(cmValue.getText())+
                Integer.valueOf(ramValue.getText())+
                Integer.valueOf(disqueValue.getText())+
                Integer.valueOf(disk2Value.getText())+
                Integer.valueOf(cgValue.getText())+
                Integer.valueOf(ventilloValue.getText())+
                Integer.valueOf(lecteurValue.getText())+
                Integer.valueOf(boitierValue.getText())+
                Integer.valueOf(alimentationValue.getText())+
                Integer.valueOf(ecranValue.getText());
    }
    
    public void updateTotalValue(){
        totalValue.setText(Integer.toString(Integer.valueOf(mergeValue.getText())+rawTotalValue));    
    }
    
    public void valueFocusLost(JTextField txtField, JComboBox combo){
        try {
            Integer.parseInt(txtField.getText());
            updateMergeValue();
        } catch (NumberFormatException e) {
            txtField.setText(new MyConnection().getValue(combo.getSelectedItem().toString(), comboPrix.getSelectedItem().toString()));
            updateMergeValue();
        }
    }
    
    public void valueKeyPressed(KeyEvent evt, JTextField txtField, JTextField nextTxtField){
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                Integer.parseInt(txtField.getText());
                updateMergeValue();
                nextTxtField.requestFocusInWindow();
            } catch (NumberFormatException e) {
                
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void loadComboValues() {
        comboCpu.setModel(new DefaultComboBoxModel(new MyConnection().getItems("cpu").toArray()));
        comboCM.setModel(new DefaultComboBoxModel(new MyConnection().getItems("cm").toArray()));
        comboRam.setModel(new DefaultComboBoxModel(new MyConnection().getItems("ram").toArray()));
        comboCG.setModel(new DefaultComboBoxModel(new MyConnection().getItems("cg").toArray()));
        comboDisque.setModel(new DefaultComboBoxModel(new MyConnection().getItems("disk").toArray()));
        comboDisque2.setModel(new DefaultComboBoxModel(new MyConnection().getItems("disk").toArray()));
        comboVentillo.setModel(new DefaultComboBoxModel(new MyConnection().getItems("ventillo").toArray()));
        comboLecteur.setModel(new DefaultComboBoxModel(new MyConnection().getItems("dvd").toArray()));
        comboBoitier.setModel(new DefaultComboBoxModel(new MyConnection().getItems("boitier").toArray()));
        comboAlimentation.setModel(new DefaultComboBoxModel(new MyConnection().getItems("alimentation").toArray()));
        comboEcran.setModel(new DefaultComboBoxModel(new MyConnection().getItems("ecran").toArray()));
    }
}

