/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devis;

import java.awt.print.PrinterException;
import javax.swing.JOptionPane;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kevin
 */
public class Print extends javax.swing.JDialog {

    /**
     * Creates new form Print
     */
    public Print(java.awt.Frame parent, String cpuDescription, String cmDescription, String ramDescription, String cgDescription, String disqueDescription, String disque2Description, String alimentationDescription, String ecranDescription, String dvdDescription,  int total) {
        super(parent);
        this.cpuDescription = cpuDescription;
        this.cmDescription = cmDescription;
        this.ramDescription = ramDescription;
        this.cgDescription = cgDescription;
        this.disqueDescription = disqueDescription;
        this.disque2Description = disque2Description;
        this.ecranDescription = ecranDescription;
        this.alimentationDescription = alimentationDescription;
        this.dvdDescription = dvdDescription;
        this.total = total;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        facture = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        facture.setEditable(false);
        facture.setColumns(20);
        facture.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        facture.setRows(5);
        jScrollPane1.setViewportView(facture);
        facture.setText("\tExpert Informatique");
        facture.append("\n\n***********************************");
        if(!this.cpuDescription.toLowerCase().equals("vide")){
            facture.append("\nCpu: "+cpuDescription);;
        }
        if(!this.cmDescription.toLowerCase().equals("vide")){
            facture.append("\nCarte Mere: "+cmDescription);
        }
        if(!this.ramDescription.toLowerCase().equals("vide")){
            facture.append("\nRam: "+ramDescription);
        }
        if(!this.disqueDescription.toLowerCase().equals("vide")){
            facture.append("\nDisque: "+disqueDescription);
        }
        if(!this.disque2Description.toLowerCase().equals("vide")){
            facture.append("\nDisque2: "+disque2Description);
        }
        if(!this.cgDescription.toLowerCase().equals("vide")){
            facture.append("\nCarte Graphique: "+cgDescription);
        }
        if(!this.alimentationDescription.toLowerCase().equals("vide")){
            facture.append("\nAlimentation: "+alimentationDescription);
        }
        if(!this.ecranDescription.toLowerCase().equals("vide")){
            facture.append("\nEcran: "+ecranDescription);
        }
        if(!this.dvdDescription.toLowerCase().equals("vide")){
            facture.append("\nAvec Graveur DVD");
        }
        facture.append("\n\n***********************************");
        facture.append("\n\n\tTOTAL: "+String.valueOf(total)+" DA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            facture.print();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "No Printer Device Found");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }
    private String cpuDescription, ramDescription, disqueDescription, disque2Description, cmDescription, cgDescription, alimentationDescription, ecranDescription, dvdDescription;
    private int total;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea facture;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
